[package]
name = "touchHLE"
version = "0.1.0"
edition = "2021"

[features]
default = ["static"]
static = ["touchHLE_dynarmic_wrapper/static"]
experimental-aarch64 = ["touchHLE_dynarmic_wrapper/experimental-aarch64"]

[workspace]
members = ["src/cpu/dynarmic_wrapper"]

[dependencies]
touchHLE_dynarmic_wrapper = { path = "src/cpu/dynarmic_wrapper" }
